### ISSUE TITLE
realsense-viewer not installed

### ISSUE THREAD

**Issue by Achllle** [2b-t/realsense-ros2-docker#3]
In the main readme in section [launching](https://github.com/2b-t/realsense-ros2-docker#2-launching) a reference is made to `realsense-viewer` but the installation instructions using binaries do not install `librealsense-utils` which has the realsense-viewer directive.

I can make a PR to add these, wanted to check first if they should be added to the default setup or as some optional tool, for example through multi-stage builds or docker compose config.

**Comment by Achllle** [comment]
Adding [sources](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md) for `librealsense2-utils` makes it install:

```
RUN mkdir -p /etc/apt/keyrings && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
RUN echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/librealsense.list
```
This needs to be added before the `apt-get install`

**Comment by 2b-t** [comment]
_Hi @Achllle_
Thanks for noticing and reporting it. Seems like I removed it by mistake back in August (see https://github.com/2b-t/realsense-ros2-docker/commit/f459a568703723d8e4e4befb97ee9caa715d145b). I will add it again.
